### ISSUE TITLE
[BUG] doesn't compile with g++ 10.2

### ISSUE THREAD

**Issue by nigeltao** [hsutter/cppfront#605]
I am on Debian Bullseye (released 2021-08-14) with g++ 10.2.

```
$ cat /etc/debian_version 
11.7
$ g++ --version | head -n 1
g++ (Debian 10.2.1-6) 10.2.1 20210110
```

`README.md` says that g++-10 should work.

```
$ git clone --quiet https://github.com/hsutter/cppfront.git
$ cd cppfront/
$ git log --oneline | head -n 1
11fc88d Switched `argv` back to its usual standard meaning
$ grep -A 2 GCC.build.instructions README.md
#### GCC build instructions

    g++-10 cppfront.cpp -std=c++20 -o cppfront
```

But it doesn't:

```
$ cd source/
$ g++-10 cppfront.cpp -std=c++20 -o /dev/null
In file included from cpp2util.h:1,
                 from reflect.h:9,
                 from sema.h:21,
                 from cppfront.cpp:18:
reflect.h2: In lambda function:
../include/cpp2util.h:688:84: error: expected ‘{’ before ‘->’ token
  688 | [&] CPP2_LAMBDA_NO_DISCARD (auto&& obj, auto&& ...params) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
      |                                                                                    ^~
reflect.h2:62:9: note: in expansion of macro ‘CPP2_UFCS’
   62 |         generated_lines.push_back( std::vector<source_line>() );
      |         ^~~~~~~~~
etc etc etc
```

---

If I apply this 1-liner patch:

```diff
diff --git a/include/cpp2util.h b/include/cpp2util.h
index 85839eb..3218f11 100644
--- a/include/cpp2util.h
+++ b/include/cpp2util.h
@@ -661,7 +661,7 @@ public:
     #define CPP2_LAMBDA_NO_DISCARD
 #else
     #define CPP2_FORCE_INLINE        __attribute__((always_inline))
-    #define CPP2_FORCE_INLINE_LAMBDA __attribute__((always_inline))
+    #define CPP2_FORCE_INLINE_LAMBDA
 
     #if defined(__clang_major__)
         //  Also check __cplusplus, only to satisfy Clang -pedantic-errors
```

then `g++-10 cppfront.cpp -std=c++20 -o /dev/null` becomes happy.

On a different machine, `g++-12` is happy without the patch. If it's a `g++-10` bug, perhaps the cppfront response is to embiggen the `10` in the `g++-10` in the `README.md` file? Or for g++, only `#define CPP2_FORCE_INLINE_LAMBDA something_non_empty` for versions > 10??

---

If you want to keep it working with g++-10, it used to compile fine with g++-10 just before commit 3b78cf171b82b2ea92f1a201922f1ec98f757bfc "Start self-hosting: half of `reflect.h` (all the metafunctions)".

```
$ # Note the ^ on the next line.
$ git checkout 3b78cf1^
Previous HEAD position was etc.
HEAD is now at 4cc69f4 Alias `cpp2util.h` in `/source` for convenience
$ g++-10 cppfront.cpp -std=c++20 -o /dev/null
$ # No error messages.

$ # Note the lack of ^ on the next line.
$ git checkout 3b78cf1
Previous HEAD position was etc.
HEAD is now at 3b78cf1 Start self-hosting: half of `reflect.h` (all the metafunctions)
$ g++-10 cppfront.cpp -std=c++20 -o /dev/null
In file included from cpp2util.h:1,
                 from reflect.h:9,
                 from sema.h:21,
                 from cppfront.cpp:18:
reflect.h2: In lambda function:
../include/cpp2util.h:682:60: error: expected ‘{’ before ‘->’ token
  682 | [&](auto&& obj, auto&& ...params) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
      |                                                            ^~
reflect.h2:426:5: note: in expansion of macro ‘CPP2_UFCS’
  426 |     t.require( t.add_member( "operator=: (virtual move this) = { }"),
      |     ^~~~~~~~~
etc etc etc
```

---

Mysteriously, though, `CPP2_FORCE_INLINE_LAMBDA` seems to exist quite happily just before the "Start self-hosting" commit.

```
$ git checkout 3b78cf1^
$ grep CPP2_FORCE_INLINE_LAMBDA ../include/*
    #define CPP2_FORCE_INLINE_LAMBDA [[msvc::forceinline]]
    #define CPP2_FORCE_INLINE_LAMBDA __attribute__((always_inline))
[&](auto&& obj, auto&& ...params) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
[&](auto&& obj) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
[&](auto&& obj, auto&& ...params) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
[&](auto&& obj) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
[](auto&& obj, auto&& ...params) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
[](auto&& obj) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
[](auto&& obj, auto&& ...params) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
[](auto&& obj) CPP2_FORCE_INLINE_LAMBDA -> decltype(auto) { \
```

I'm not sure what exactly of the `source/reflect.{h,h2}` changes caused the trouble.

**Comment by hsutter** [comment]
Thanks! Interestingly, GCC 10 has always been working on my builds, but I see I've been using 10.3 and you're using 10.2.

I'll try to apply the patch you suggest -- how does this look?

```
        #if (__GNUC__ * 100 + __GNUC_MINOR__) < 1003
            #undef CPP2_FORCE_INLINE_LAMBDA
        #endif
```

**Comment by JohelEGP** [comment]
It has to be defined to expand to nothing.

**Comment by nigeltao** [comment]
Yeah, what @JohelEGP said. However:

```
$ git diff
diff --git a/include/cpp2util.h b/include/cpp2util.h
index 0181129..a89499b 100644
--- a/include/cpp2util.h
+++ b/include/cpp2util.h
@@ -661,7 +661,13 @@ public:
     #define CPP2_LAMBDA_NO_DISCARD
 #else
     #define CPP2_FORCE_INLINE        __attribute__((always_inline))
-    #define CPP2_FORCE_INLINE_LAMBDA __attribute__((always_inline))
+
+    #if defined(__GNUC__) && !defined(__clang_major__) && (((__GNUC__ * 100) + __GNUC_MINOR__) < 1003)
+        // https://github.com/hsutter/cppfront/issues/605
+        #define CPP2_FORCE_INLINE_LAMBDA
+    #else
+        #define CPP2_FORCE_INLINE_LAMBDA __attribute__((always_inline))
+    #endif
 
     #if defined(__clang_major__)
         //  Also check __cplusplus, only to satisfy Clang -pedantic-errors

$ g++-10 cppfront.cpp -std=c++20 -o /dev/null
$ # The previous command (g++-10 etc) gave no errors.
```
